# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Github\Image-Labelling\Labelling.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Image = QtWidgets.QLabel(self.centralwidget)
        self.label_Image.setText("")
        self.label_Image.setObjectName("label_Image")
        self.verticalLayout.addWidget(self.label_Image)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 4, 1, 1)
        self.lineEdit_size = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_size.sizePolicy().hasHeightForWidth())
        self.lineEdit_size.setSizePolicy(sizePolicy)
        self.lineEdit_size.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_size.setFont(font)
        self.lineEdit_size.setObjectName("lineEdit_size")
        self.gridLayout.addWidget(self.lineEdit_size, 2, 2, 1, 1)
        self.label_tl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_tl.setFont(font)
        self.label_tl.setObjectName("label_tl")
        self.gridLayout.addWidget(self.label_tl, 0, 1, 1, 1)
        self.lineEdit_br = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_br.sizePolicy().hasHeightForWidth())
        self.lineEdit_br.setSizePolicy(sizePolicy)
        self.lineEdit_br.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_br.setFont(font)
        self.lineEdit_br.setObjectName("lineEdit_br")
        self.gridLayout.addWidget(self.lineEdit_br, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.label_br = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_br.setFont(font)
        self.label_br.setObjectName("label_br")
        self.gridLayout.addWidget(self.label_br, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 4, 1, 1)
        self.label_generate = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_generate.sizePolicy().hasHeightForWidth())
        self.label_generate.setSizePolicy(sizePolicy)
        self.label_generate.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_generate.setFont(font)
        self.label_generate.setText("")
        self.label_generate.setObjectName("label_generate")
        self.gridLayout.addWidget(self.label_generate, 2, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_size = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_size.setFont(font)
        self.label_size.setObjectName("label_size")
        self.gridLayout.addWidget(self.label_size, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 4, 1, 1)
        self.label_path_annotation = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_path_annotation.sizePolicy().hasHeightForWidth())
        self.label_path_annotation.setSizePolicy(sizePolicy)
        self.label_path_annotation.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_path_annotation.setFont(font)
        self.label_path_annotation.setText("")
        self.label_path_annotation.setObjectName("label_path_annotation")
        self.gridLayout.addWidget(self.label_path_annotation, 1, 5, 1, 1)
        self.lineEdit_tl = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tl.sizePolicy().hasHeightForWidth())
        self.lineEdit_tl.setSizePolicy(sizePolicy)
        self.lineEdit_tl.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_tl.setFont(font)
        self.lineEdit_tl.setObjectName("lineEdit_tl")
        self.gridLayout.addWidget(self.lineEdit_tl, 0, 2, 1, 1)
        self.label_path_image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_path_image.sizePolicy().hasHeightForWidth())
        self.label_path_image.setSizePolicy(sizePolicy)
        self.label_path_image.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_path_image.setFont(font)
        self.label_path_image.setText("")
        self.label_path_image.setObjectName("label_path_image")
        self.gridLayout.addWidget(self.label_path_image, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_A = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Resources/backward_page_200px_1189181_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_A.setIcon(icon)
        self.action_A.setObjectName("action_A")
        self.action_D = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Resources/forward_page_200px_1189511_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_D.setIcon(icon1)
        self.action_D.setObjectName("action_D")
        self.action_E = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Resources/delete_201px_1189401_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_E.setIcon(icon2)
        self.action_E.setObjectName("action_E")
        self.action_Q = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Resources/close_256px_1159854_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Q.setIcon(icon3)
        self.action_Q.setObjectName("action_Q")
        self.toolBar.addAction(self.action_A)
        self.toolBar.addAction(self.action_D)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_E)
        self.toolBar.addAction(self.action_Q)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "图像目录"))
        self.label_tl.setText(_translate("MainWindow", "左上角点"))
        self.label_br.setText(_translate("MainWindow", "右下角点"))
        self.pushButton_3.setText(_translate("MainWindow", "生成目录"))
        self.label_size.setText(_translate("MainWindow", "边框尺寸"))
        self.pushButton_2.setText(_translate("MainWindow", "标注目录"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_A.setText(_translate("MainWindow", "上一张(A)"))
        self.action_A.setToolTip(_translate("MainWindow", "上一张(A)"))
        self.action_A.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.action_D.setText(_translate("MainWindow", "下一张(D)"))
        self.action_D.setToolTip(_translate("MainWindow", "下一张(D)"))
        self.action_D.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.action_E.setText(_translate("MainWindow", "删除(E)"))
        self.action_E.setToolTip(_translate("MainWindow", "删除(E)"))
        self.action_E.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_Q.setText(_translate("MainWindow", "退出(Q)"))
        self.action_Q.setShortcut(_translate("MainWindow", "Ctrl+Q"))
import Labelling_rc
